notifications:
  email:
    on_success: change
    on_failure: always

sudo: false
language: python
matrix:
  include:
    - python: '2.7'
    - python: '3.5'
    - python: '3.6'
    - python: '3.7'
    - python: '3.8-dev'
    - python: '3.6'
      env: TOXENV=flake8

install:
  - pip install -U pip wheel setuptools
  - pip install -U Cython
  - pip install -U tox-travis tox

script:
  - tox
